services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    ports:
      - "8000:8000"  # Laravel dev server
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - APP_NAME=ListOfTopBrands
      - APP_URL=http://localhost:8000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=list_of_top_brands
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - LOG_STACK=daily
      - FILESYSTEM_DRIVER=public


  angular:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"  # Angular dev server
    volumes:
      - ./resources/angular:/var/www/resources/angular
    working_dir: /var/www/resources/angular

  db:
    image: mysql:8.0
    platform: linux/amd64  # M1 compatibility
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=list_of_top_brands
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
