FROM node:22

# Install Angular CLI globally
RUN npm install -g @angular/cli

WORKDIR /var/www/resources/angular

# Install dependencies and start dev server
CMD ["npm", "install", "&&", "npm", "start"]
